### ISSUE TITLE
SSR For APollo Client an gatsby

### ISSUE THREAD

**Issue by shreyas-1997** [jlengstorf/gatsby-with-apollo#15]
Hi Bro I reallly Need your i implemented the gatsby with apollo client.. it works fine for client side but i want to show all the data to server side rendereing which can be seen in view source but how can i apply SSR for apollo client and gatsby please help me..
i created a folder by name apollo inside components and inside apollo folder i create two file client.js and wraproot element.js
see the screenshot
Client.js

![image](https://user-images.githubusercontent.com/66195578/95475625-0a7a3600-09a4-11eb-947a-03a80f113349.png)

Wrap-root-element.js
![image](https://user-images.githubusercontent.com/66195578/95475635-0f3eea00-09a4-11eb-8756-1bde493439a0.png)

this is screenshot which i refered the code from your repo by i want to add SSR so that all the data can be view in view source please bro guide me to add SSR in this project i am stuck in this part since one month

**Comment by shreyas-1997** [comment]
Please Reply

**Comment by jlengstorf** [comment]
the easiest way to SSR GraphQL in Gatsby is to use [`gatsby-source-graphql`](https://www.gatsbyjs.com/plugins/gatsby-source-graphql/), which is designed for loading data at build time and putting the data in the source code. Apollo is better used for client-side GraphQL in Gatsby — if you prefer Apollo for SSR, you may not need Gatsby at all

hope that helps!
