### ISSUE TITLE
What about running the same queries

### ISSUE THREAD

**Issue by laurenskling** [jlengstorf/gatsby-with-apollo#17]
Thanks for this demo guys. I'm running a similar setup. My challenge is, that I want to run the same kind of queries both in Gatsby and in ApolloClient. I want my search page to render the first 10 results from Gatsby, after that, the user can search and filter with live data via ApolloClient. Also, I have a client-only route fetching for an item that hasn't built yet. All of this works, _if_ I set up 2 different queries. Because the shape is just a bit different. `gatsby-source-graphql` wraps the query with an extra `something` parent, typenames get prepended with `SOMETHING_`. This wouldn't be too bad if I could share the requested fields between the gatsby `graphql``` and apolloClient `gql``` but gatsby wont allow me to interpolate variables into the graphql block.

Hope anyone has any idea's to share more between the 2

**Comment by jlengstorf** [comment]
you could potentially use a fragment, but unfortunately Gatsby's GraphQL setup isn't compatible with other tools, so you'll probably need the two queries 😕 

you may want to ask on one of Gatsby's official channels? they might know something I don't

**Comment by laurenskling** [comment]
Thanks for the response @jlengstorf , I'll try to explore elsewhere.
