### ISSUE TITLE
Dead graphql endpoint

### ISSUE THREAD

**Issue by gentleShark** [jlengstorf/gatsby-with-apollo#3]
The graphql endpoint in the code no longer works and is hosted on https://launchpad.graphql.com which was sunset on Dec 15, 2018. 

This endpoint is a working substitute (however you will need to change the client side dog query to some other query to get a valid response since dog is no longer a root query): 
https://rickandmortyapi.com/graphql/

**Comment by reinbeumer** [comment]
If you want the same grqphql server, querys and data, use this => https://codesandbox.io/s/32ypr38l61 from the apollo website => https://www.apollographql.com/docs/react/essentials/queries/.
This generates an (temp?) sample graphql server for you.
Just change the client.js uri of this project to the generated url on the browser pannel on the right.
All the rest stays the same.

**Comment by jlengstorf** [comment]
This will be fixed in #6.
