### ISSUE TITLE
Receive new data at Runtime - Question

### ISSUE THREAD

**Issue by ngprnk** [jlengstorf/gatsby-with-apollo#5]
Saw the code 

```
// This query is executed at build time by Gatsby.
export const GatsbyQuery = graphql`
  {
    rickAndMorty {
      character(id: 1) {
        name
        image
      }
    }
  }
`;
```

The comment says query is executed at build time by Gatsby.

does this mean that if any new data is available in the backend it has to be re build again ? to receive the new data ? 

Just wanted to ask a question because i didn't see any other ways to reach out. Sorry for cluttering the issues.

**Comment by jlengstorf** [comment]
Yes, any queries run at build time would require a rebuild to pick up new data. You can use Webhooks to automate this, or set up a cron job to rebuild the site on a regular schedule.

Hope that helps!
